//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeTests.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1, -2, +3, +1.
        /// </summary>
        internal static string D01_E1 {
            get {
                return ResourceManager.GetString("D01_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1, +1, +1.
        /// </summary>
        internal static string D01_E2 {
            get {
                return ResourceManager.GetString("D01_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1, +1, -2.
        /// </summary>
        internal static string D01_E3 {
            get {
                return ResourceManager.GetString("D01_E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1, -2, -3.
        /// </summary>
        internal static string D01_E4 {
            get {
                return ResourceManager.GetString("D01_E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1, -1.
        /// </summary>
        internal static string D01_E5 {
            get {
                return ResourceManager.GetString("D01_E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3, +3, +4, -2, -4.
        /// </summary>
        internal static string D01_E6 {
            get {
                return ResourceManager.GetString("D01_E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6, +3, +8, +5, -6.
        /// </summary>
        internal static string D01_E7 {
            get {
                return ResourceManager.GetString("D01_E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +7, +7, -2, -7, -4.
        /// </summary>
        internal static string D01_E8 {
            get {
                return ResourceManager.GetString("D01_E8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +9
        ///+1
        ///-11
        ///+12
        ///+17
        ///-6
        ///+14
        ///-1
        ///-17
        ///+5
        ///-6
        ///-10
        ///-14
        ///+9
        ///+12
        ///-10
        ///-13
        ///+10
        ///-9
        ///+4
        ///-17
        ///-11
        ///+17
        ///+20
        ///-15
        ///-13
        ///+17
        ///-10
        ///+19
        ///-15
        ///+10
        ///-3
        ///-14
        ///-3
        ///-6
        ///-18
        ///-14
        ///+1
        ///-19
        ///+11
        ///-12
        ///+17
        ///-2
        ///-8
        ///+16
        ///+15
        ///+6
        ///-1
        ///+6
        ///-17
        ///+20
        ///-6
        ///-19
        ///-18
        ///-1
        ///+3
        ///-19
        ///-16
        ///+11
        ///-5
        ///+16
        ///-5
        ///-2
        ///-11
        ///-1
        ///-2
        ///+9
        ///-8
        ///-8
        ///-11
        ///-19
        ///-6
        ///-14
        ///+13
        ///-14
        ///-7
        ///-6
        ///+16
        ///-15
        ///+8
        ///-1
        ///-14
        ///+2
        ///+8
        ///-19
        ///+2
        ///+3
        ///-16
        ///+6
        ///-9
        ///-6
        ///-14
        ///+18
        ///+4
        ///+9
        ///+1
        ///+3
        ///-10
        ///+13
        ///-17
        ///+16
        ///+19
        ///+18
        ///+20
        ///+4
        ///-9
        ///-16
        ///+18
        ///-10
        ///+15
        ///-12
        ///+16        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D01_Puzzle {
            get {
                return ResourceManager.GetString("D01_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdef,bababc,abbcde,abcccd,aabcdd,abcdee,ababab.
        /// </summary>
        internal static string D02_E1 {
            get {
                return ResourceManager.GetString("D02_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcde,fghij,klmno,pqrst,fguij,axcye,wvxyz.
        /// </summary>
        internal static string D02_E2 {
            get {
                return ResourceManager.GetString("D02_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uosnxmfkezbojfdgwvrtaqhluy
        ///iosnxmfkazbcopdgnvrtaqhluy
        ///ioanxmfkezbcjpdgwvrjaohluy
        ///uosnxmfkezbcjpjgwvrtaqhlut
        ///imsnxmfkezbcjpugwvataqhluy
        ///ioenxmfkezbcjpdgwvrraqhluz
        ///iosnxmfkezbcjpdgevitnqhluy
        ///iosnxmfkezcccpdgcvrtaqhluy
        ///loinxmfkezbcjpdgwvrtaqhluu
        ///iosnlmfkezbczndgwvrtaqhluy
        ///iosnxmfkezbcjpdgwvrifghluy
        ///iosnuhfkezbcjpugwvrtaqhluy
        ///iosnxmfkezbcwpdgwvrtaihlgy
        ///iosnxzfwuzbcjpdgwvrtaqhluy
        ///hosnxmfjizbcjpdgwvrtaqhluy
        ///iornxmfktzbcjpdgwvrtaqhluo
        ///nosnxmfkdzbcjpdgwvrtaqhlwy
        ///iosnxmfkezbcjpdgwvrtaktluq
        ///ioszxmlk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D02_Puzzle {
            get {
                return ResourceManager.GetString("D02_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 1,3: 4x4
        ///#2 @ 3,1: 4x4
        ///#3 @ 5,5: 2x2.
        /// </summary>
        internal static string D03_E1 {
            get {
                return ResourceManager.GetString("D03_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 469,741: 22x26
        ///#2 @ 290,985: 25x11
        ///#3 @ 794,639: 21x28
        ///#4 @ 969,266: 13x11
        ///#5 @ 465,103: 24x10
        ///#6 @ 537,925: 7x9
        ///#7 @ 276,540: 17x25
        ///#8 @ 386,614: 12x8
        ///#9 @ 38,207: 12x21
        ///#10 @ 836,338: 29x21
        ///#11 @ 728,948: 19x23
        ///#12 @ 555,514: 18x14
        ///#13 @ 572,754: 29x12
        ///#14 @ 181,225: 21x21
        ///#15 @ 383,414: 21x14
        ///#16 @ 22,726: 29x29
        ///#17 @ 989,671: 11x17
        ///#18 @ 750,176: 13x26
        ///#19 @ 492,757: 29x11
        ///#20 @ 330,179: 28x25
        ///#21 @ 192,230: 15x24
        ///#22 @ 495,968: 21x24
        ///#23 @ 413,522: 13x16
        ///#24 @ 888,886: 25x14 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D03_Puzzle {
            get {
                return ResourceManager.GetString("D03_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-11-01 00:00] Guard #10 begins shift
        ///[1518-11-01 00:05] falls asleep
        ///[1518-11-01 00:25] wakes up
        ///[1518-11-01 00:30] falls asleep
        ///[1518-11-01 00:55] wakes up
        ///[1518-11-01 23:58] Guard #99 begins shift
        ///[1518-11-02 00:40] falls asleep
        ///[1518-11-02 00:50] wakes up
        ///[1518-11-03 00:05] Guard #10 begins shift
        ///[1518-11-03 00:24] falls asleep
        ///[1518-11-03 00:29] wakes up
        ///[1518-11-04 00:02] Guard #99 begins shift
        ///[1518-11-04 00:36] falls asleep
        ///[1518-11-04 00:46] wakes up
        ///[1518-11-05 00:03] Guard #99 b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D04_E1 {
            get {
                return ResourceManager.GetString("D04_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-04-22 00:56] falls asleep
        ///[1518-07-23 00:09] falls asleep
        ///[1518-10-29 00:02] falls asleep
        ///[1518-07-29 00:58] wakes up
        ///[1518-03-18 00:15] falls asleep
        ///[1518-11-08 00:02] Guard #2851 begins shift
        ///[1518-02-28 00:43] falls asleep
        ///[1518-06-24 00:52] wakes up
        ///[1518-06-08 00:29] falls asleep
        ///[1518-09-18 00:30] falls asleep
        ///[1518-07-07 00:00] Guard #3433 begins shift
        ///[1518-11-01 00:53] falls asleep
        ///[1518-09-04 00:00] Guard #3433 begins shift
        ///[1518-08-14 00:48] wakes up
        ///[1518-06-19 00:43] wakes u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D04_Puzzle {
            get {
                return ResourceManager.GetString("D04_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3
        ///-2
        ///-1
        ///0
        ///1
        ///2
        ///3.
        /// </summary>
        internal static string HelperIntArray {
            get {
                return ResourceManager.GetString("HelperIntArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcd
        ///efgh
        ///jkl.
        /// </summary>
        internal static string HelperStringArray {
            get {
                return ResourceManager.GetString("HelperStringArray", resourceCulture);
            }
        }
    }
}
