//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeTests.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1, -2, +3, +1.
        /// </summary>
        internal static string D01_E1 {
            get {
                return ResourceManager.GetString("D01_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1, +1, +1.
        /// </summary>
        internal static string D01_E2 {
            get {
                return ResourceManager.GetString("D01_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1, +1, -2.
        /// </summary>
        internal static string D01_E3 {
            get {
                return ResourceManager.GetString("D01_E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1, -2, -3.
        /// </summary>
        internal static string D01_E4 {
            get {
                return ResourceManager.GetString("D01_E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1, -1.
        /// </summary>
        internal static string D01_E5 {
            get {
                return ResourceManager.GetString("D01_E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3, +3, +4, -2, -4.
        /// </summary>
        internal static string D01_E6 {
            get {
                return ResourceManager.GetString("D01_E6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -6, +3, +8, +5, -6.
        /// </summary>
        internal static string D01_E7 {
            get {
                return ResourceManager.GetString("D01_E7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +7, +7, -2, -7, -4.
        /// </summary>
        internal static string D01_E8 {
            get {
                return ResourceManager.GetString("D01_E8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +9
        ///+1
        ///-11
        ///+12
        ///+17
        ///-6
        ///+14
        ///-1
        ///-17
        ///+5
        ///-6
        ///-10
        ///-14
        ///+9
        ///+12
        ///-10
        ///-13
        ///+10
        ///-9
        ///+4
        ///-17
        ///-11
        ///+17
        ///+20
        ///-15
        ///-13
        ///+17
        ///-10
        ///+19
        ///-15
        ///+10
        ///-3
        ///-14
        ///-3
        ///-6
        ///-18
        ///-14
        ///+1
        ///-19
        ///+11
        ///-12
        ///+17
        ///-2
        ///-8
        ///+16
        ///+15
        ///+6
        ///-1
        ///+6
        ///-17
        ///+20
        ///-6
        ///-19
        ///-18
        ///-1
        ///+3
        ///-19
        ///-16
        ///+11
        ///-5
        ///+16
        ///-5
        ///-2
        ///-11
        ///-1
        ///-2
        ///+9
        ///-8
        ///-8
        ///-11
        ///-19
        ///-6
        ///-14
        ///+13
        ///-14
        ///-7
        ///-6
        ///+16
        ///-15
        ///+8
        ///-1
        ///-14
        ///+2
        ///+8
        ///-19
        ///+2
        ///+3
        ///-16
        ///+6
        ///-9
        ///-6
        ///-14
        ///+18
        ///+4
        ///+9
        ///+1
        ///+3
        ///-10
        ///+13
        ///-17
        ///+16
        ///+19
        ///+18
        ///+20
        ///+4
        ///-9
        ///-16
        ///+18
        ///-10
        ///+15
        ///-12
        ///+16        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D01_P1 {
            get {
                return ResourceManager.GetString("D01_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdef,bababc,abbcde,abcccd,aabcdd,abcdee,ababab.
        /// </summary>
        internal static string D02_E1 {
            get {
                return ResourceManager.GetString("D02_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcde,fghij,klmno,pqrst,fguij,axcye,wvxyz.
        /// </summary>
        internal static string D02_E2 {
            get {
                return ResourceManager.GetString("D02_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uosnxmfkezbojfdgwvrtaqhluy
        ///iosnxmfkazbcopdgnvrtaqhluy
        ///ioanxmfkezbcjpdgwvrjaohluy
        ///uosnxmfkezbcjpjgwvrtaqhlut
        ///imsnxmfkezbcjpugwvataqhluy
        ///ioenxmfkezbcjpdgwvrraqhluz
        ///iosnxmfkezbcjpdgevitnqhluy
        ///iosnxmfkezcccpdgcvrtaqhluy
        ///loinxmfkezbcjpdgwvrtaqhluu
        ///iosnlmfkezbczndgwvrtaqhluy
        ///iosnxmfkezbcjpdgwvrifghluy
        ///iosnuhfkezbcjpugwvrtaqhluy
        ///iosnxmfkezbcwpdgwvrtaihlgy
        ///iosnxzfwuzbcjpdgwvrtaqhluy
        ///hosnxmfjizbcjpdgwvrtaqhluy
        ///iornxmfktzbcjpdgwvrtaqhluo
        ///nosnxmfkdzbcjpdgwvrtaqhlwy
        ///iosnxmfkezbcjpdgwvrtaktluq
        ///ioszxmlk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D02_P1 {
            get {
                return ResourceManager.GetString("D02_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -3
        ///-2
        ///-1
        ///0
        ///1
        ///2
        ///3.
        /// </summary>
        internal static string HelperIntArray {
            get {
                return ResourceManager.GetString("HelperIntArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcd
        ///efgh
        ///jkl.
        /// </summary>
        internal static string HelperStringArray {
            get {
                return ResourceManager.GetString("HelperStringArray", resourceCulture);
            }
        }
    }
}
